import type { MenuPermissionDef } from '@/types'

export const menuPermissionMap: MenuPermissionDef[] = [
  {
    key: 'dashboard',
    label: '仪表盘',
    icon: 'DataAnalysis',
    path: '/',
    resources: ['dashboard'],
  },
  {
    key: 'task',
    label: '任务管理',
    icon: 'List',
    path: '/tasks',
    resources: ['task'],
  },
  {
    key: 'log',
    label: '任务日志',
    icon: 'Document',
    path: '/logs',
    resources: ['log'],
  },
  {
    key: 'executor',
    label: '执行器',
    icon: 'Cpu',
    path: '/executors',
    resources: ['executor'],
  },
  {
    key: 'data-query',
    label: '数据查询',
    icon: 'Search',
    path: '',
    resources: ['datasource'],
    children: [
      {
        key: 'datasource',
        label: '数据源管理',
        icon: 'Connection',
        path: '/datasources',
        resources: ['datasource'],
      },
      {
        key: 'sql-query',
        label: 'SQL 查询',
        icon: 'Search',
        path: '/sql-query',
        resources: ['datasource'],
      },
      {
        key: 'query-history',
        label: '查询历史',
        icon: 'List',
        path: '/query-history',
        resources: ['datasource'],
      },
      {
        key: 'saved-sql',
        label: '已保存 SQL',
        icon: 'Document',
        path: '/saved-sql',
        resources: ['datasource'],
      },
    ],
  },
  {
    key: 'system-admin',
    label: '系统管理',
    icon: 'Setting',
    path: '',
    resources: ['user', 'role', 'domain', 'config', 'audit_log', 'webhook'],
    children: [
      {
        key: 'user-management',
        label: '用户管理',
        icon: 'User',
        path: '/admin/users',
        resources: ['user'],
      },
      {
        key: 'role-management',
        label: '角色管理',
        icon: 'Key',
        path: '/admin/roles',
        resources: ['role'],
      },
      {
        key: 'domain-management',
        label: '领域管理',
        icon: 'Grid',
        path: '/admin/domains',
        resources: ['domain'],
      },
      {
        key: 'webhook-management',
        label: 'Webhook管理',
        icon: 'Connection',
        path: '/admin/webhooks',
        resources: ['webhook'],
      },
      {
        key: 'system-config',
        label: '系统配置',
        icon: 'Operation',
        path: '/admin/system-config',
        resources: ['config'],
      },
      {
        key: 'audit-log',
        label: '审计日志',
        icon: 'Notebook',
        path: '/admin/audit-logs',
        resources: ['audit_log'],
      },
    ],
  },
]
