// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId            string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	CurrentLoad           int32                  `protobuf:"varint,2,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	RunningExecutionIds   []string               `protobuf:"bytes,3,rep,name=running_execution_ids,json=runningExecutionIds,proto3" json:"running_execution_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *HeartbeatRequest) GetRunningExecutionIds() []string {
	if x != nil {
		return x.RunningExecutionIds
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId    string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTaskRequest) Reset() {
	*x = SubscribeTaskRequest{}
	mi := &file_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTaskRequest) ProtoMessage() {}

func (x *SubscribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTaskRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeTaskRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config         string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryInterval  int32                  `protobuf:"varint,7,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Task) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RetryTimes    int32                  `protobuf:"varint,8,opt,name=retry_times,json=retryTimes,proto3" json:"retry_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ReportTaskResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTaskResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportTaskResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportTaskResultRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportTaskResultRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportTaskResultRequest) GetRetryTimes() int32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportTaskLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogContent    string                 `protobuf:"bytes,4,opt,name=log_content,json=logContent,proto3" json:"log_content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogRequest) Reset() {
	*x = ReportTaskLogRequest{}
	mi := &file_proto_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogRequest) ProtoMessage() {}

func (x *ReportTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskLogRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportTaskLogRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskLogRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ReportTaskLogRequest) GetLogContent() string {
	if x != nil {
		return x.LogContent
	}
	return ""
}

func (x *ReportTaskLogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReportTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogResponse) Reset() {
	*x = ReportTaskLogResponse{}
	mi := &file_proto_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogResponse) ProtoMessage() {}

func (x *ReportTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTaskLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_executor_proto protoreflect.FileDescriptor

const file_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executor.proto\x12\tbdopsflow\"|\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12!\n" +
	"\fcurrent_load\x18\x02 \x01(\x05R\vcurrentLoad\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x14SubscribeTaskRequest\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\"\xdf\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12%\n" +
	"\x0eretry_interval\x18\a \x01(\x05R\rretryInterval\"\xf6\x01\n" +
	"\x17ReportTaskResultRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1f\n" +
	"\vretry_times\x18\b \x01(\x05R\n" +
	"retryTimes\"N\n" +
	"\x18ReportTaskResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xae\x01\n" +
	"\x14ReportTaskLogRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x12\x1f\n" +
	"\vlog_content\x18\x04 \x01(\tR\n" +
	"logContent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"K\n" +
	"\x15ReportTaskLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x94\x03\n" +
	"\x0fExecutorService\x12C\n" +
	"\bRegister\x12\x1a.bdopsflow.RegisterRequest\x1a\x1b.bdopsflow.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.bdopsflow.HeartbeatRequest\x1a\x1c.bdopsflow.HeartbeatResponse\x12C\n" +
	"\rSubscribeTask\x12\x1f.bdopsflow.SubscribeTaskRequest\x1a\x0f.bdopsflow.Task0\x01\x12[\n" +
	"\x10ReportTaskResult\x12\".bdopsflow.ReportTaskResultRequest\x1a#.bdopsflow.ReportTaskResultResponse\x12R\n" +
	"\rReportTaskLog\x12\x1f.bdopsflow.ReportTaskLogRequest\x1a .bdopsflow.ReportTaskLogResponseB#Z!github.com/lynnyq/bdopsflow/protob\x06proto3"

var (
	file_proto_executor_proto_rawDescOnce sync.Once
	file_proto_executor_proto_rawDescData []byte
)

func file_proto_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)))
	})
	return file_proto_executor_proto_rawDescData
}

var file_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_executor_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: bdopsflow.RegisterRequest
	(*RegisterResponse)(nil),         // 1: bdopsflow.RegisterResponse
	(*HeartbeatRequest)(nil),         // 2: bdopsflow.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 3: bdopsflow.HeartbeatResponse
	(*SubscribeTaskRequest)(nil),     // 4: bdopsflow.SubscribeTaskRequest
	(*Task)(nil),                     // 5: bdopsflow.Task
	(*ReportTaskResultRequest)(nil),  // 6: bdopsflow.ReportTaskResultRequest
	(*ReportTaskResultResponse)(nil), // 7: bdopsflow.ReportTaskResultResponse
	(*ReportTaskLogRequest)(nil),     // 8: bdopsflow.ReportTaskLogRequest
	(*ReportTaskLogResponse)(nil),    // 9: bdopsflow.ReportTaskLogResponse
}
var file_proto_executor_proto_depIdxs = []int32{
	0, // 0: bdopsflow.ExecutorService.Register:input_type -> bdopsflow.RegisterRequest
	2, // 1: bdopsflow.ExecutorService.Heartbeat:input_type -> bdopsflow.HeartbeatRequest
	4, // 2: bdopsflow.ExecutorService.SubscribeTask:input_type -> bdopsflow.SubscribeTaskRequest
	6, // 3: bdopsflow.ExecutorService.ReportTaskResult:input_type -> bdopsflow.ReportTaskResultRequest
	8, // 4: bdopsflow.ExecutorService.ReportTaskLog:input_type -> bdopsflow.ReportTaskLogRequest
	1, // 5: bdopsflow.ExecutorService.Register:output_type -> bdopsflow.RegisterResponse
	3, // 6: bdopsflow.ExecutorService.Heartbeat:output_type -> bdopsflow.HeartbeatResponse
	5, // 7: bdopsflow.ExecutorService.SubscribeTask:output_type -> bdopsflow.Task
	7, // 8: bdopsflow.ExecutorService.ReportTaskResult:output_type -> bdopsflow.ReportTaskResultResponse
	9, // 9: bdopsflow.ExecutorService.ReportTaskLog:output_type -> bdopsflow.ReportTaskLogResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_executor_proto_init() }
func file_proto_executor_proto_init() {
	if File_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_proto_depIdxs,
		MessageInfos:      file_proto_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_proto = out.File
	file_proto_executor_proto_goTypes = nil
	file_proto_executor_proto_depIdxs = nil
}
