// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 正在运行任务的详细状态信息
type RunningTaskState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId     string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId          int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress        int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`                                     // 进度 0-100
	ProgressMessage string                 `protobuf:"bytes,4,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"` // 进度信息
	StartTime       int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                  // 开始时间戳（Unix秒）
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // 任务状态：running, pending 等
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunningTaskState) Reset() {
	*x = RunningTaskState{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTaskState) ProtoMessage() {}

func (x *RunningTaskState) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTaskState.ProtoReflect.Descriptor instead.
func (*RunningTaskState) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *RunningTaskState) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunningTaskState) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RunningTaskState) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *RunningTaskState) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

func (x *RunningTaskState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RunningTaskState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExecutorName  string                 `protobuf:"bytes,3,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	Duplicate     bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *RegisterResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type HeartbeatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName        string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	CurrentLoad         int32                  `protobuf:"varint,2,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	RunningExecutionIds []string               `protobuf:"bytes,3,rep,name=running_execution_ids,json=runningExecutionIds,proto3" json:"running_execution_ids,omitempty"`
	// 新增：携带正在运行任务的详细状态（可选，用于新调度器任务恢复）
	RunningTasks []*RunningTaskState `protobuf:"bytes,4,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	// 新增：表示此心跳是否是在检测到调度器变化后的首次心跳
	IsReconnect   bool `protobuf:"varint,5,opt,name=is_reconnect,json=isReconnect,proto3" json:"is_reconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *HeartbeatRequest) GetRunningExecutionIds() []string {
	if x != nil {
		return x.RunningExecutionIds
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningTasks() []*RunningTaskState {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

func (x *HeartbeatRequest) GetIsReconnect() bool {
	if x != nil {
		return x.IsReconnect
	}
	return false
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TargetCapacity int32                  `protobuf:"varint,3,opt,name=target_capacity,json=targetCapacity,proto3" json:"target_capacity,omitempty"`
	// 新增：调度器是否希望执行器下次心跳时发送详细任务状态
	NeedFullSync bool `protobuf:"varint,4,opt,name=need_full_sync,json=needFullSync,proto3" json:"need_full_sync,omitempty"`
	// 新增：调度器节点ID（用于检测调度器变化）
	SchedulerNodeId string `protobuf:"bytes,5,opt,name=scheduler_node_id,json=schedulerNodeId,proto3" json:"scheduler_node_id,omitempty"`
	// 新增：是否是新的领导节点
	IsNewLeader bool `protobuf:"varint,6,opt,name=is_new_leader,json=isNewLeader,proto3" json:"is_new_leader,omitempty"`
	// 新增：该节点当前是否是领导节点
	IsLeader bool `protobuf:"varint,7,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// 新增：需要取消的任务执行ID列表
	CancelExecutionIds []string `protobuf:"bytes,8,rep,name=cancel_execution_ids,json=cancelExecutionIds,proto3" json:"cancel_execution_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetTargetCapacity() int32 {
	if x != nil {
		return x.TargetCapacity
	}
	return 0
}

func (x *HeartbeatResponse) GetNeedFullSync() bool {
	if x != nil {
		return x.NeedFullSync
	}
	return false
}

func (x *HeartbeatResponse) GetSchedulerNodeId() string {
	if x != nil {
		return x.SchedulerNodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetIsNewLeader() bool {
	if x != nil {
		return x.IsNewLeader
	}
	return false
}

func (x *HeartbeatResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *HeartbeatResponse) GetCancelExecutionIds() []string {
	if x != nil {
		return x.CancelExecutionIds
	}
	return nil
}

type SubscribeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName  string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTaskRequest) Reset() {
	*x = SubscribeTaskRequest{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTaskRequest) ProtoMessage() {}

func (x *SubscribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTaskRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeTaskRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config         string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount     int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryInterval  int32                  `protobuf:"varint,7,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Task) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RetryTimes    int32                  `protobuf:"varint,8,opt,name=retry_times,json=retryTimes,proto3" json:"retry_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTaskResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportTaskResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportTaskResultRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ReportTaskResultRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ReportTaskResultRequest) GetRetryTimes() int32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportTaskLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogContent    string                 `protobuf:"bytes,4,opt,name=log_content,json=logContent,proto3" json:"log_content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogRequest) Reset() {
	*x = ReportTaskLogRequest{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogRequest) ProtoMessage() {}

func (x *ReportTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTaskLogRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportTaskLogRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskLogRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ReportTaskLogRequest) GetLogContent() string {
	if x != nil {
		return x.LogContent
	}
	return ""
}

func (x *ReportTaskLogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReportTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskLogResponse) Reset() {
	*x = ReportTaskLogResponse{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskLogResponse) ProtoMessage() {}

func (x *ReportTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskLogResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *ReportTaskLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressRequest) Reset() {
	*x = ReportTaskProgressRequest{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressRequest) ProtoMessage() {}

func (x *ReportTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *ReportTaskProgressRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReportTaskProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressResponse) Reset() {
	*x = ReportTaskProgressResponse{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressResponse) ProtoMessage() {}

func (x *ReportTaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *ReportTaskProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTaskProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 新添加：同步正在运行任务的请求
type SyncRunningTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName  string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunningTasksRequest) Reset() {
	*x = SyncRunningTasksRequest{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunningTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunningTasksRequest) ProtoMessage() {}

func (x *SyncRunningTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunningTasksRequest.ProtoReflect.Descriptor instead.
func (*SyncRunningTasksRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *SyncRunningTasksRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

// 新添加：同步正在运行任务的响应
type SyncRunningTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RunningTasks  []*RunningTaskState    `protobuf:"bytes,3,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRunningTasksResponse) Reset() {
	*x = SyncRunningTasksResponse{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRunningTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRunningTasksResponse) ProtoMessage() {}

func (x *SyncRunningTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRunningTasksResponse.ProtoReflect.Descriptor instead.
func (*SyncRunningTasksResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

func (x *SyncRunningTasksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncRunningTasksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncRunningTasksResponse) GetRunningTasks() []*RunningTaskState {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\tbdopsflow\"\xcc\x01\n" +
	"\x10RunningTaskState\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12)\n" +
	"\x10progress_message\x18\x04 \x01(\tR\x0fprogressMessage\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"[\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"\x89\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rexecutor_name\x18\x03 \x01(\tR\fexecutorName\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate\"\xf3\x01\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\x12!\n" +
	"\fcurrent_load\x18\x02 \x01(\x05R\vcurrentLoad\x122\n" +
	"\x15running_execution_ids\x18\x03 \x03(\tR\x13runningExecutionIds\x12@\n" +
	"\rrunning_tasks\x18\x04 \x03(\v2\x1b.bdopsflow.RunningTaskStateR\frunningTasks\x12!\n" +
	"\fis_reconnect\x18\x05 \x01(\bR\visReconnect\"\xb5\x02\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ftarget_capacity\x18\x03 \x01(\x05R\x0etargetCapacity\x12$\n" +
	"\x0eneed_full_sync\x18\x04 \x01(\bR\fneedFullSync\x12*\n" +
	"\x11scheduler_node_id\x18\x05 \x01(\tR\x0fschedulerNodeId\x12\"\n" +
	"\ris_new_leader\x18\x06 \x01(\bR\visNewLeader\x12\x1b\n" +
	"\tis_leader\x18\a \x01(\bR\bisLeader\x120\n" +
	"\x14cancel_execution_ids\x18\b \x03(\tR\x12cancelExecutionIds\";\n" +
	"\x14SubscribeTaskRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\"\xdf\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12%\n" +
	"\x0eretry_interval\x18\a \x01(\x05R\rretryInterval\"\xf6\x01\n" +
	"\x17ReportTaskResultRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1f\n" +
	"\vretry_times\x18\b \x01(\x05R\n" +
	"retryTimes\"N\n" +
	"\x18ReportTaskResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xae\x01\n" +
	"\x14ReportTaskLogRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x12\x1f\n" +
	"\vlog_content\x18\x04 \x01(\tR\n" +
	"logContent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"K\n" +
	"\x15ReportTaskLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x19ReportTaskProgressRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"P\n" +
	"\x1aReportTaskProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x17SyncRunningTasksRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\"\x90\x01\n" +
	"\x18SyncRunningTasksResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\rrunning_tasks\x18\x03 \x03(\v2\x1b.bdopsflow.RunningTaskStateR\frunningTasks2\xd4\x04\n" +
	"\x0fExecutorService\x12C\n" +
	"\bRegister\x12\x1a.bdopsflow.RegisterRequest\x1a\x1b.bdopsflow.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.bdopsflow.HeartbeatRequest\x1a\x1c.bdopsflow.HeartbeatResponse\x12C\n" +
	"\rSubscribeTask\x12\x1f.bdopsflow.SubscribeTaskRequest\x1a\x0f.bdopsflow.Task0\x01\x12[\n" +
	"\x10ReportTaskResult\x12\".bdopsflow.ReportTaskResultRequest\x1a#.bdopsflow.ReportTaskResultResponse\x12R\n" +
	"\rReportTaskLog\x12\x1f.bdopsflow.ReportTaskLogRequest\x1a .bdopsflow.ReportTaskLogResponse\x12a\n" +
	"\x12ReportTaskProgress\x12$.bdopsflow.ReportTaskProgressRequest\x1a%.bdopsflow.ReportTaskProgressResponse\x12[\n" +
	"\x10SyncRunningTasks\x12\".bdopsflow.SyncRunningTasksRequest\x1a#.bdopsflow.SyncRunningTasksResponseB#Z!github.com/lynnyq/bdopsflow/protob\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_executor_proto_goTypes = []any{
	(*RunningTaskState)(nil),           // 0: bdopsflow.RunningTaskState
	(*RegisterRequest)(nil),            // 1: bdopsflow.RegisterRequest
	(*RegisterResponse)(nil),           // 2: bdopsflow.RegisterResponse
	(*HeartbeatRequest)(nil),           // 3: bdopsflow.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 4: bdopsflow.HeartbeatResponse
	(*SubscribeTaskRequest)(nil),       // 5: bdopsflow.SubscribeTaskRequest
	(*Task)(nil),                       // 6: bdopsflow.Task
	(*ReportTaskResultRequest)(nil),    // 7: bdopsflow.ReportTaskResultRequest
	(*ReportTaskResultResponse)(nil),   // 8: bdopsflow.ReportTaskResultResponse
	(*ReportTaskLogRequest)(nil),       // 9: bdopsflow.ReportTaskLogRequest
	(*ReportTaskLogResponse)(nil),      // 10: bdopsflow.ReportTaskLogResponse
	(*ReportTaskProgressRequest)(nil),  // 11: bdopsflow.ReportTaskProgressRequest
	(*ReportTaskProgressResponse)(nil), // 12: bdopsflow.ReportTaskProgressResponse
	(*SyncRunningTasksRequest)(nil),    // 13: bdopsflow.SyncRunningTasksRequest
	(*SyncRunningTasksResponse)(nil),   // 14: bdopsflow.SyncRunningTasksResponse
}
var file_executor_proto_depIdxs = []int32{
	0,  // 0: bdopsflow.HeartbeatRequest.running_tasks:type_name -> bdopsflow.RunningTaskState
	0,  // 1: bdopsflow.SyncRunningTasksResponse.running_tasks:type_name -> bdopsflow.RunningTaskState
	1,  // 2: bdopsflow.ExecutorService.Register:input_type -> bdopsflow.RegisterRequest
	3,  // 3: bdopsflow.ExecutorService.Heartbeat:input_type -> bdopsflow.HeartbeatRequest
	5,  // 4: bdopsflow.ExecutorService.SubscribeTask:input_type -> bdopsflow.SubscribeTaskRequest
	7,  // 5: bdopsflow.ExecutorService.ReportTaskResult:input_type -> bdopsflow.ReportTaskResultRequest
	9,  // 6: bdopsflow.ExecutorService.ReportTaskLog:input_type -> bdopsflow.ReportTaskLogRequest
	11, // 7: bdopsflow.ExecutorService.ReportTaskProgress:input_type -> bdopsflow.ReportTaskProgressRequest
	13, // 8: bdopsflow.ExecutorService.SyncRunningTasks:input_type -> bdopsflow.SyncRunningTasksRequest
	2,  // 9: bdopsflow.ExecutorService.Register:output_type -> bdopsflow.RegisterResponse
	4,  // 10: bdopsflow.ExecutorService.Heartbeat:output_type -> bdopsflow.HeartbeatResponse
	6,  // 11: bdopsflow.ExecutorService.SubscribeTask:output_type -> bdopsflow.Task
	8,  // 12: bdopsflow.ExecutorService.ReportTaskResult:output_type -> bdopsflow.ReportTaskResultResponse
	10, // 13: bdopsflow.ExecutorService.ReportTaskLog:output_type -> bdopsflow.ReportTaskLogResponse
	12, // 14: bdopsflow.ExecutorService.ReportTaskProgress:output_type -> bdopsflow.ReportTaskProgressResponse
	14, // 15: bdopsflow.ExecutorService.SyncRunningTasks:output_type -> bdopsflow.SyncRunningTasksResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
